docker-build: &docker-build
  run:
    name: Build Docker image
    command: |
      docker build -t adobe/commerce-cif-ci-env:${TAG:-$CIRCLE_TAG} ./ci/environment

docker-push: &docker-push
  run:
    name: Push image to Docker Hub
    command: |
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      docker push adobe/commerce-cif-ci-env:${TAG:-$CIRCLE_TAG}

version: 2
jobs:
  build:
    docker:
      - image: adobe/commerce-cif-ci-env:v0.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: node ci/build.js
      - store_test_results:
          path: test/results
      - store_artifacts:
          path: test/results

  release:
    docker:
      - image: adobe/commerce-cif-ci-env:v0.0.1
    steps:
      - checkout
      - run:
          name: Release
          command: node ci/release.js

  build-ci-image:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    environment:
      TAG: latest
    steps:
      - checkout
      - setup_remote_docker
      - *docker-build

  push-ci-image-latest:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    environment:
      TAG: latest
    steps:
      - checkout
      - setup_remote_docker
      - *docker-build
      - *docker-push

  push-ci-image-tag:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - *docker-build
      - *docker-push

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^@(.+)@release-(major|minor|patch)$/

  build-and-push-ci-image:
    jobs:
      - build-ci-image:
          filters:
            tags:
              only: /.*/
      - push-ci-image-latest:
          requires:
            - build-ci-image
          filters:
            branches:
              only: master
      - push-ci-image-tag:
          requires:
            - build-ci-image
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^ci-v.*$/
